### ISSUE TITLE
how to collect download lists from hitomi.la seach result？

### ISSUE THREAD

**Issue by lukemin** [HDoujinDownloader/HDoujin-Downloader#10]
eg：
https://hitomi.la/search.html?language%3Achinese%20female%3Aloli
The result shows 536 pages，I wanna collect all the lists to a txt file. Is it possible to add this function?

**Comment by HDoujinDownloader** [comment]
There is no support for adding search results to the queue at the moment. However, you can add tag URLs to the queue if you update to version [`2020.12.24.5-alpha`](https://github.com/HDoujinDownloader/HDoujin-Downloader/releases/tag/v2020.12.24.0-alpha) and replace the `Hitomi.lua` module in `modules\lua\` with [this updated one](https://gist.github.com/HDoujinDownloader/175b42589451cac206fd1ec647b034b1) (I haven't updated it in the module repository yet because it requires APIs that are currently only available in the alpha release).

Adding URLs such as `https://hitomi.la/index-chinese.html` will add all of the galleries on the page to the queue. To add multiple pages, use the URL generation feature under `Manga > Add from List` to generate all page URLs (e.g. an example template might look like `https://hitomi.la/index-chinese.html?page=(1-2728)`).

I realize this is not ideal and not as fine-grained as the search result URL you'd like to add, so I'll work on getting those working shortly.

**Comment by lukemin** [comment]
A bit complicated, waiting for a simplified way.
