### ISSUE TITLE
It downloads folders, but no actual files on Mangasee123

### ISSUE THREAD

**Issue by lolkimbo** [HDoujinDownloader/HDoujin-Downloader#3]
I have no idea how to fix this

**Comment by HDoujinDownloader** [comment]
Thanks for the report! Someone else reported a similar issue with the different site; the underlying problem is the same here (there was a bug introduced with the last update in how the program handles relative image URLs).

It should be fixed now with [v2020.8.4.0](https://github.com/HDoujinDownloader/HDoujin-Downloader/releases/tag/v2020.8.4.0).
